name: Move Issue on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Move associated issue to Done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          issue_number=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/events | jq -r '.[] | select(.event=="connected") | .issue.number')
          if [ -n "$issue_number" ]; then
            project_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/ES2-UFPI/Remedius/projects | jq -r '.[] | select(.name=="Remedius's project") | .id')
            column_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/projects/$project_id/columns | jq -r '.[] | select(.name=="Done") | .id')
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/projects/columns/$column_id/cards -d '{"content_id":'$issue_number', "content_type":"Issue"}'
          fi
        fi
